steps:
- id: "clone-repo"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./clone-git-repository.sh"
- id: "remove-microservices"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./remove-microservices.sh"
  - ${_PROJECT_ID}
  - ${_CLUSTER_LABEL}
  - ${_MONOLITH_SERVICE}
  waitFor:
  - "clone-repo"
- id: "remove-monolith"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./remove-monolith-in-asm.sh"
  - ${_PROJECT_ID}
  - ${_CLUSTER_LABEL}
  - ${_MONOLITH_SERVICE}
  waitFor:
  - "remove-microservices"
substitutions:
  _PROJECT_ID: ""
  _CLUSTER_LABEL: ""
  _MONOLITH_SERVICE: ""

