steps:
- id: "clone-repo"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./clone-git-repository.sh"
- id: "remove-monolith"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./remove-monolith.sh"
  - ${_PROJECT_ID}
  - ${_GCP_ZONE}
  - ${_CLUSTER_LABEL}
  waitFor:
  - "clone-repo"
- id: "remove-microservices"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./remove-microservices.sh"
  - ${_PROJECT_ID}
  - ${_GCP_ZONE}
  - ${_CLUSTER_LABEL}
  waitFor:
  - "clone-repo"
substitutions:
  _PROJECT_ID: ""
  _GCP_ZONE: ""
  _CLUSTER_LABEL: ""

