steps:
- id: "clone-repo"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./clone-git-repository.sh"
- id: "deploy-monolith"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./deploy-monolith-in-asm.sh"
  - ${_PROJECT_ID}
  - ${_CLUSTER_LABEL}
  waitFor:
  - "clone-repo"
- id: "deploy-microservices"
  name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args:
  - "./deploy-microservices.sh"
  - ${_PROJECT_ID}
  - ${_CLUSTER_LABEL}
  waitFor:
  - "deploy-monolith"
substitutions:
  _PROJECT_ID: ""
  _CLUSTER_LABEL: ""
