apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-monolith:5432/postgresdb
#  SPRING_DATASOURCE_URL: jdbc:postgresql://34.122.244.181:5432/postgresdb?gssEncMode=disable
  SPRING_DATASOURCE_USERNAME: postgres # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: password # should match POSTGRES_PASSWORD
